# Generated by Django 3.2.3 on 2021-05-22 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام شرکت سازنده')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='نام')),
                ('last_name', models.CharField(max_length=30, verbose_name='نام خانوادگی')),
                ('address', models.TextField(max_length=200, verbose_name='آدرس ')),
                ('postal_code', models.IntegerField(max_length=20, null=True, verbose_name='کد پستی')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره همراه')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='نام')),
                ('last_name', models.CharField(max_length=30, verbose_name='نام خانوادگی')),
            ],
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام')),
                ('color', models.CharField(max_length=8, verbose_name='رنگ')),
                ('size', models.CharField(max_length=2, verbose_name='سایز')),
                ('number', models.IntegerField(max_length=5, verbose_name='تعداد')),
                ('status', models.CharField(choices=[('available', 'Available'), ('out_of_stock', 'Out of stock')], default='Out of stock', max_length=20)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoes_shop.company')),
            ],
        ),
        migrations.CreateModel(
            name='OrderRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('number', models.IntegerField(max_length=5, verbose_name='تعداد')),
                ('customer_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoes_shop.customer')),
                ('employee_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoes_shop.employee')),
                ('shoe_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoes_shop.shoes')),
            ],
        ),
    ]
